version: '3.8'
services:
  brreview:
    build:
      context: .
    container_name: brreview_app
    env_file: .env
    volumes:
      - ./brreview:/app
    ports:
      - "8811:8000"
    restart: unless-stopped
